# Librerías

Las <span style="color:gold">librerías</span> o <span style="color:gold">bibliotecas</span> de Python son colecciones de módulos y funciones predefinidas que permiten a los usuarios ahorrar\
tiempo y esfuerzo al utilizar código ya creado y probado para realizar tareas específicas.

# Numpy

In [1]:
import numpy as np

## Vectores

In [2]:
vector = np.array([1, 2, 3, 4, 5])

In [3]:
print(vector)

[1 2 3 4 5]


In [4]:
type(vector)

numpy.ndarray

In [5]:
vector.dtype

dtype('int32')

In [8]:
vector.astype(float)

dtype('int32')

In [9]:
vector[2:5]

array([3, 4, 5])

In [12]:
vector[0] = 10
print(vector)

[10  2  3  4  5]


In [13]:
copia_vector = vector.copy()

In [18]:
copia_vector.astype(float)

array([10.,  2.,  5.,  4.,  5.])

In [19]:
copia_vector[2] = 3.1416

In [22]:
copia_vector

array([10,  2,  3,  4,  5])

In [24]:
vector

array([10,  2,  3,  4,  5])

In [23]:
vector_desordenado = np.array([3, 1, 2, 5, 4, 8, 7, 10, 14, 12, 20])

In [25]:
np.sort(vector_desordenado)

array([ 1,  2,  3,  4,  5,  7,  8, 10, 12, 14, 20])

## Matrices

In [34]:
matriz = np.array([[1, 2, 3, 4], [4, 5, 6, 4], [7, 8, 9, 4]])
print(matriz)

[[1 2 3 4]
 [4 5 6 4]
 [7 8 9 4]]


In [35]:
matriz.shape

(3, 4)

In [40]:
matriz[:, 1]

array([2, 5, 8])

In [43]:
matriz[1:, :]

array([[4, 5, 6, 4],
       [7, 8, 9, 4]])

In [44]:
matriz.size

12

In [46]:
matriz.reshape((4, 3))

array([[1, 2, 3],
       [4, 4, 5],
       [6, 4, 7],
       [8, 9, 4]])

In [49]:
matriz.reshape((1, 12))

array([[1, 2, 3, 4, 4, 5, 6, 4, 7, 8, 9, 4]])

In [50]:
matriz

array([[1, 2, 3, 4],
       [4, 5, 6, 4],
       [7, 8, 9, 4]])

In [51]:
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9],
       [4, 4, 4]])

In [52]:
matriz.flatten()

array([1, 2, 3, 4, 4, 5, 6, 4, 7, 8, 9, 4])

### Operar entre matrices

In [54]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 0], [0, -1]])

In [55]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[-1  0]
 [ 0 -1]]


In [56]:
np.hstack([A, B])

array([[ 1,  2, -1,  0],
       [ 3,  4,  0, -1]])

In [57]:
np.vstack([A, B])

array([[ 1,  2],
       [ 3,  4],
       [-1,  0],
       [ 0, -1]])

In [58]:
np.concatenate([A, B], axis=0)

array([[ 1,  2],
       [ 3,  4],
       [-1,  0],
       [ 0, -1]])

In [59]:
np.concatenate([A, B], axis=1)

array([[ 1,  2, -1,  0],
       [ 3,  4,  0, -1]])

In [60]:
np.zeros(shape=(3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones(shape=(3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Álgebra Lineal

In [62]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [63]:
print(v1+v2)

[5 7 9]


In [64]:
print(v1-v2)

[-3 -3 -3]


In [65]:
print(v1*v2)

[ 4 10 18]


In [66]:
print(v1/v2)

[0.25 0.4  0.5 ]


In [67]:
np.dot(v1, v2)

32

### Arreglo de booleanos

In [68]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [69]:
mask = x > 2
print(mask)

[False False  True  True  True]


In [71]:
np.where(x > 2, 0, 1)

array([1, 1, 0, 0, 0])

### Medidas estadísticas

In [72]:
print(x)

[1 2 3 4 5]


In [73]:
x.sum()

15

In [74]:
x.max()

5

In [75]:
x.min()

1

In [76]:
x.mean()

3.0

In [77]:
x.var()

2.0

In [78]:
x.std()

1.4142135623730951

## Constantes de numpy

In [79]:
np.inf

inf

In [80]:
np.nan

nan

In [81]:
np.e

2.718281828459045

In [82]:
np.pi

3.141592653589793

## Espacios lineales

In [83]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.linspace(0, 128, 64)

array([  0.        ,   2.03174603,   4.06349206,   6.0952381 ,
         8.12698413,  10.15873016,  12.19047619,  14.22222222,
        16.25396825,  18.28571429,  20.31746032,  22.34920635,
        24.38095238,  26.41269841,  28.44444444,  30.47619048,
        32.50793651,  34.53968254,  36.57142857,  38.6031746 ,
        40.63492063,  42.66666667,  44.6984127 ,  46.73015873,
        48.76190476,  50.79365079,  52.82539683,  54.85714286,
        56.88888889,  58.92063492,  60.95238095,  62.98412698,
        65.01587302,  67.04761905,  69.07936508,  71.11111111,
        73.14285714,  75.17460317,  77.20634921,  79.23809524,
        81.26984127,  83.3015873 ,  85.33333333,  87.36507937,
        89.3968254 ,  91.42857143,  93.46031746,  95.49206349,
        97.52380952,  99.55555556, 101.58730159, 103.61904762,
       105.65079365, 107.68253968, 109.71428571, 111.74603175,
       113.77777778, 115.80952381, 117.84126984, 119.87301587,
       121.9047619 , 123.93650794, 125.96825397, 128.  

### Aleatorios

In [91]:
np.random.random(10)

array([1.54732331e-04, 7.90773301e-01, 2.86976538e-01, 7.18575009e-01,
       1.22446356e-01, 2.79589873e-01, 7.80841635e-01, 4.25715705e-01,
       2.78431802e-01, 3.72842193e-01])

In [92]:
rng = np.random.default_rng()

In [93]:
rng.random()

0.12949258533097618

In [94]:
rng.uniform(0, 5)

0.41230200903747016

In [95]:
rng.integers(0, 5)

1

In [96]:
rng.normal(size=(2, 2))

array([[ 1.13442634, -0.87025098],
       [-0.12909077, -0.18472668]])